name: Semantic Convention Test table
on:
  push:
    tags: [ '**' ]
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/semconvgen-check.yml
      - 'spec/**'

jobs:
  test-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Verify tables are up-to-date
      run: docker run --rm thisthatdc/semconvgen -f ./data-source markdown -md ./spec --md-check