name: Semantic Convention Test table
on:
  push:
    tags: [ '**' ]
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/semconvgen-check.yml
      - 'spec/**'

jobs:
  test-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: List directories
      run: |
        pwd
        ls -alR
    - name: Verify tables are up-to-date
      run: docker run --rm -v<yaml-path>:/source -v<output-path>:/spec thisthatdc/semconvgen -f /source markdown -md /spec --md-check