name: Semantic Convention Update Tables
on:
  push:
    tags: [ '**' ]
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/semconvgen-check.yml
      - 'data-source/**'

jobs:
  test-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verify tables are up-to-date
      run: docker run --rm -v $(pwd)/data-source:/source -v $(pwd)/spec:/spec thisthatdc/semconvgen -f /source markdown -md /spec
    - name: Check file changes
      run: |
        git diff
        git status
    - name: commit diff
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Automatic Table generation"
        git push